services:
  pz:
    image: delath/pz
    container_name: pz
    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"
    volumes:
      - ./Zomboid:/home/pzuser/Zomboid
      - ./Server:/home/pzuser/server
    restart: 'unless-stopped'
