services:
  rust:
    image: delath/rust
    container_name: rust
    ports:
      - "28015:28015/tcp"
      - "28015:28015/udp"
      - "28016:28016/udp"
      - "28082:28082/tcp"
    volumes:
      - ./Server:/home/rust/server
    restart: 'unless-stopped'
