services:
  valheim:
    image: delath/valheim
    container_name: valheim
    ports:
      - "2456:2456"
      - "2457:2457"
    volumes:
      - ./World:/home/valheim/.config/unity3d/IronGate/Valheim
      - ./Server:/home/valheim/server/.config/unity3d/IronGate/Valheim
    restart: 'unless-stopped'
