version: '3.8'

services:
  minecraft:
    image: delath/minecraft
    container_name: minecraft
    ports:
      - "25565:25565"
    volumes:
      - ./world:/home/minecraft/world
    restart: 'unless-stopped'
