version: '3.8'

services:
  terraria:
    image: delath/terraria
    container_name: terraria
    ports:
      - "7777:7777"
    volumes:
      - ./Worlds:/home/terraria/Worlds
    restart: 'unless-stopped'