services:
  terraria:
    image: delath/terraria
    container_name: terraria
    ports:
      - "7777:7777"
    volumes:
      - ./world:/home/terraria/world
    restart: 'unless-stopped'
    tty: true