version: '3.8'

services:
  skyblock:
    image: delath/skyblock
    container_name: skyblock
    ports:
      - "25565:25565"
    volumes:
      - ./world:/home/skyblock/server
    restart: 'unless-stopped'
